MvcCoreApiClient/Models/ErrorViewModel.cs
namespace MvcCoreApiClient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreApiClient/Models/Hospital.cs
using Newtonsoft.Json;

namespace MvcCoreApiClient.Models
{
    
    public class Hospital
    {
        [JsonProperty("idHospital")]
        public int Id { get; set; }

        [JsonProperty("nombre")]
        public string Nombre { get; set; }

        [JsonProperty("direccion")]
        public string Direccion { get; set; }

        [JsonProperty("telefono")]
        public string Telefono { get; set; }

        [JsonProperty("camas")]
        public int Camas { get; set; }
    }
}

MvcCoreApiClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreApiClient.Models;

namespace MvcCoreApiClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreApiClient/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreApiClient.Models;
using MvcCoreApiClient.Services;

namespace MvcCoreApiClient.Controllers
{
    public class HospitalesController : Controller
    {

        private ServiceHospitales service;

        public HospitalesController(ServiceHospitales service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Servidor()
        {
            List<Hospital> hospitales = await this.service.GetHospitalesAsync();
            return View(hospitales);
        }

        public async Task<IActionResult> Details(int id)
        {
            Hospital hospital = await this.service.FindHospitalAsync(id);
            return View(hospital);
        }
         public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cliente()
        {
            return View();
        }
    }
}

MvcCoreApiClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <button id="botonLoad" class="btn btn-outline-success">Load Personas</button>
    <table id="tablapersonas" class="table table-dark" >
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Email</th>
                <th>Edad</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section Scripts {
    <script>
        $(document).ready(function() {
            $("#botonLoad").click(function(){
                var url = "https://apipersonassofia.azurewebsites.net/api/personas";
                $.ajax({
                    url: url,
                    method: "GET",
                    success: function(data){
                        var html = "";
                        $.each(data, function(index, persona){
                            html += "<tr>";
                            html += "<td>" + persona.nombre + "</td>";
                            html += "<td>" + persona.email + "</td>";
                            html += "<td>" + persona.edad + "</td>";
                            html += "</tr>";
                        })
                        $("#tablapersonas tbody").html(html);
                    }
                })
            })
        })
    </script>
}

MvcCoreApiClient/Views/Hospitales/Cliente.cshtml
<h1>Consumo Api Hospitales Clientes</h1>

<button id="botonhospital">Load Hospitales</button>
<table id="tablahospitales" class="table table-info">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Telefono</th>
            <th>Camas</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function(){
            $("#botonhospital").click(function(){
                var url = "https://apicorehospitalessmg.azurewebsites.net/api/hospitales";
                $.ajax({
                    url: url,
                    method: "GET",
                    success: function(data){
                        var html = "";
                        $.each(data, function(index, hospital){
                            html += "<tr>";
                            html += "<td>" + hospital.nombre + "</td>";
                            html += "<td>" + hospital.direccion + "</td>";
                            html += "<td>" + hospital.telefono + "</td>";
                            html += "<td>" + hospital.camas + "</td>";
                            html += "</tr>";
                        })
                        $("#tablahospitales tbody").html(html);
                    }
                })
            })
        })
    </script>
}

MvcCoreApiClient/Views/Hospitales/Details.cshtml
@model MvcCoreApiClient.Models.Hospital

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Camas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Camas)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcCoreApiClient/Views/Hospitales/Index.cshtml
<h2>Menu hospitales</h2>

<ul>
    <li>
        <a asp-controller="Hospitales" asp-action="Cliente">Api Hospitales cliente</a>
    </li>
    <li>
        <a asp-controller="Hospitales" asp-action="Servidor">Api Hospitales servidor</a>
    </li>
</ul>

MvcCoreApiClient/Views/Hospitales/Servidor.cshtml
@model IEnumerable<MvcCoreApiClient.Models.Hospital>

@{
    ViewData["Title"] = "Servidor";
}

<h1>Servidor</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Camas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Camas)
            </td>
            <td>
                <a asp-controller="Hospitales" asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreApiClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreApiClient</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreApiClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreApiClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Hospitales" asp-action="Index">Hospitales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcCoreApiClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>